### ISSUE TITLE
Current status isn't pushed if album is None.

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/mpd-mqtt-gateway#1] opened 2018-02-06 18:23 UTC
I don't know if this occurs with other combinations.

```
2018-02-06 19:19:34,836:INFO:MainThread:gateway:Starting mpd mqtt gateway
2018-02-06 19:19:34,836:INFO:MpdReaderThread:gateway:MPD worker started
2018-02-06 19:19:34,836:INFO:MqttWriterThread:gateway:MQTT worker started
2018-02-06 19:19:34,836:INFO:MpdReaderThread:gateway:Connecting to mpd server at mpd:6600
2018-02-06 19:19:34,836:INFO:MqttWriterThread:gateway:Connecting to mqtt server at mqttserver:1883
2018-02-06 19:19:34,837:INFO:MpdReaderThread:mpd:Calling MPD connect('mpd', 6600, timeout=None)
2018-02-06 19:19:34,850:INFO:MqttWriterThread:gateway:Connected to mqtt server
2018-02-06 19:19:34,852:INFO:MpdReaderThread:gateway:Connected to mpd server, version: 0.20.0
2018-02-06 19:19:34,854:INFO:MpdReaderThread:gateway:Detected new metadata: {'title': 'foo', 'artist': 'bar', 'album': None}
2018-02-06 19:19:34,855:INFO:MqttWriterThread:gateway:Pushing metadata to topic 'music': {'title': 'foo', 'artist': 'bar', 'album': None}
```

This looks okay, but nothing is being pushed to MQTT.

**Comment by msteinhoff** [comment] 2018-02-06 19:41
Caused by me being to dumb to use the correct python format strings when building mqtt topic strings.

Fixed in dff0b64.

**Closed by msteinhoff** 2018-02-06 19:41 UTC
